# AX7203 / AX7203B clock input
set_property PACKAGE_PIN R4 [get_ports sys_clk_p]
set_property PACKAGE_PIN T4 [get_ports sys_clk_n]
set_property IOSTANDARD LVDS_25 [get_ports {sys_clk_p sys_clk_n}]

# AX7203 user keys, active low
set_property PACKAGE_PIN J21 [get_ports key1_n]
set_property PACKAGE_PIN E13 [get_ports key2_n]
set_property IOSTANDARD LVCMOS33 [get_ports key1_n]
set_property IOSTANDARD LVCMOS33 [get_ports key2_n]

# AX7203 user LEDs, active low
set_property PACKAGE_PIN B13 [get_ports led1]
set_property PACKAGE_PIN C13 [get_ports led2]
set_property PACKAGE_PIN D14 [get_ports led3]
set_property PACKAGE_PIN D15 [get_ports led4]
set_property IOSTANDARD LVCMOS33 [get_ports led1]
set_property IOSTANDARD LVCMOS33 [get_ports led2]
set_property IOSTANDARD LVCMOS33 [get_ports led3]
set_property IOSTANDARD LVCMOS33 [get_ports led4]

# AX7203 USB-UART bridge
set_property PACKAGE_PIN P20 [get_ports uart_rxd]
set_property PACKAGE_PIN N15 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_txd]

# AN706 ADC on AX7203 J11
set_property PACKAGE_PIN P15 [get_ports {ad7606_os[2]}]
set_property PACKAGE_PIN P16 [get_ports {ad7606_os[1]}]
set_property PACKAGE_PIN R17 [get_ports {ad7606_os[0]}]
set_property PACKAGE_PIN R16 [get_ports ad7606_convstab]
set_property PACKAGE_PIN N17 [get_ports ad7606_rd]
set_property PACKAGE_PIN P17 [get_ports ad7606_reset]
set_property PACKAGE_PIN U16 [get_ports ad7606_busy]
set_property PACKAGE_PIN T16 [get_ports ad7606_cs]
set_property PACKAGE_PIN U18 [get_ports ad7606_first_data]
set_property PACKAGE_PIN V18 [get_ports {ad7606_data[0]}]
set_property PACKAGE_PIN V19 [get_ports {ad7606_data[1]}]
set_property PACKAGE_PIN U20 [get_ports {ad7606_data[2]}]
set_property PACKAGE_PIN V20 [get_ports {ad7606_data[3]}]
set_property PACKAGE_PIN AA9 [get_ports {ad7606_data[4]}]
set_property PACKAGE_PIN AB10 [get_ports {ad7606_data[5]}]
set_property PACKAGE_PIN AA10 [get_ports {ad7606_data[6]}]
set_property PACKAGE_PIN AA11 [get_ports {ad7606_data[7]}]
set_property PACKAGE_PIN W10 [get_ports {ad7606_data[8]}]
set_property PACKAGE_PIN V10 [get_ports {ad7606_data[9]}]
set_property PACKAGE_PIN Y12 [get_ports {ad7606_data[10]}]
set_property PACKAGE_PIN Y11 [get_ports {ad7606_data[11]}]
set_property PACKAGE_PIN W12 [get_ports {ad7606_data[12]}]
set_property PACKAGE_PIN W11 [get_ports {ad7606_data[13]}]
set_property PACKAGE_PIN AA15 [get_ports {ad7606_data[14]}]
set_property PACKAGE_PIN AB15 [get_ports {ad7606_data[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_os[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606_convstab]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606_rd]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606_reset]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606_busy]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606_cs]
set_property IOSTANDARD LVCMOS33 [get_ports ad7606_first_data]
set_property IOSTANDARD LVCMOS33 [get_ports {ad7606_data[*]}]

# AN430 LCD on AX7203 J13
set_property PACKAGE_PIN W16 [get_ports {lcd_r[0]}]
set_property PACKAGE_PIN W15 [get_ports {lcd_r[1]}]
set_property PACKAGE_PIN V17 [get_ports {lcd_r[2]}]
set_property PACKAGE_PIN W17 [get_ports {lcd_r[3]}]
set_property PACKAGE_PIN U15 [get_ports {lcd_r[4]}]
set_property PACKAGE_PIN V15 [get_ports {lcd_r[5]}]
set_property PACKAGE_PIN AB21 [get_ports {lcd_r[6]}]
set_property PACKAGE_PIN AB22 [get_ports {lcd_r[7]}]
set_property PACKAGE_PIN AA21 [get_ports {lcd_g[0]}]
set_property PACKAGE_PIN AA20 [get_ports {lcd_g[1]}]
set_property PACKAGE_PIN AB20 [get_ports {lcd_g[2]}]
set_property PACKAGE_PIN AA19 [get_ports {lcd_g[3]}]
set_property PACKAGE_PIN AA18 [get_ports {lcd_g[4]}]
set_property PACKAGE_PIN AB18 [get_ports {lcd_g[5]}]
set_property PACKAGE_PIN T20 [get_ports {lcd_g[6]}]
set_property PACKAGE_PIN Y17 [get_ports {lcd_g[7]}]
set_property PACKAGE_PIN W22 [get_ports {lcd_b[0]}]
set_property PACKAGE_PIN W21 [get_ports {lcd_b[1]}]
set_property PACKAGE_PIN T21 [get_ports {lcd_b[2]}]
set_property PACKAGE_PIN U21 [get_ports {lcd_b[3]}]
set_property PACKAGE_PIN Y21 [get_ports {lcd_b[4]}]
set_property PACKAGE_PIN Y22 [get_ports {lcd_b[5]}]
set_property PACKAGE_PIN W20 [get_ports {lcd_b[6]}]
set_property PACKAGE_PIN W19 [get_ports {lcd_b[7]}]
set_property PACKAGE_PIN Y19 [get_ports lcd_dclk]
set_property PACKAGE_PIN Y18 [get_ports lcd_hs]
set_property PACKAGE_PIN V22 [get_ports lcd_vs]
set_property PACKAGE_PIN U22 [get_ports lcd_de]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_dclk]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_hs]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_vs]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_de]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]

create_clock -name sys_clk_200m -period 5.000 [get_ports sys_clk_p]
create_generated_clock -name pixel_clk -source [get_ports sys_clk_p] -divide_by 22 [get_pins pixel_clock_divider_inst/clk_out_reg/Q]
